### PR TITLE
Replace tabs with spaces

### PR DESCRIPTION
**Pull request by fitzgen**
Not trying to start a style flame war, but...

The mixed tabs and spaces was making indentation really funky in Emacs, and
since there was more spaces indenting than tabs, I moved everything over to
spaces.

### CODE REVIEW

**Comment by eeide** [comment]
If this were to be merged, it would be smart, I think, to rig things so that Emacs won't use tabs for indentation in this file in the future. One can do this by setting `indent-tabs-mode` to `nil` with a file-local variable.

**Comment by eeide** [comment]
Also, unless I am mistaken, the indentation in the current file is not "funky" if one uses 8-character tabs, which is the Emacs default.

**Comment by cbsmith** [comment]
If you're going to do anything, use SmartTabs: https://www.emacswiki.org/emacs/SmartTabs

**Comment by fitzgen** [comment]
I guess I changed tabs to be 4 characters wide at some point in time.

Regardless, choosing tabs or spaces seems better than mixing tabs and spaces. I don't really have a strong opinion, nor should my opinion really matter since I'm not a maintainer of this project, I simply offered this PR in the hopes that it is useful :)

**Comment by regehr** [comment]
Eric, if we do this is there a convenient commit hook we can use to scan for tabs getting added back in?

**Comment by eeide** [comment]
@regehr I don't know how to install such a (pre-)commit hook at GitHub. I would be interested in learning how to do such a thing, though.

Probably, one of the many existing GitHub "service integrations" has some way of doing this, but I don't know which one or how to configure it.

The closest thing that I know how to do would be to fail the Travis-CI build—which would enforce a kind of "punishment," but doesn't prevent the push from happening. Oh, and the "configure Emacs to follow the rule" thing I mentioned in an earlier comment.

**Comment by regehr** [comment]
Yeah I know about "configure emacs" but I seem to make a mistake here or there since I commit to C-Reduce from like a half-dozen machines

**Comment by eeide** [comment]
@regehr The "configure Emacs" thing I mentioned earlier puts the config in the file itself, so unless you tell Emacs to ignore file-local variables, you'd be good.

**Comment by eeide** [comment]
Of course, if somebody ever used an editor other than Emacs, there would still be "issues."

**Comment by regehr** [comment]
Ok, I'd be happy for us to do that. In the meantime merging.

**Pull request merged**
