### PR TITLE
r242834

### PR DESCRIPTION
**Pull request by yrnkrn**

### CODE REVIEW

**Comment by eeide** [comment]
The Travis-CI build for this pull request failed—no doubt because it uses LLVM 3.6. (Hooray for our new Travis-CI build bot!)

@yrnkrn, can you amend your pull request with patches that allow the Travis-CI build to succeed?

I can work on this, too, although I probably won't be able to get to this for a few days.

**Comment by yrnkrn** [comment]
I'd guess the change required would be to replace the apt-get llvm-3.6 command in the travis to get the nightly build according to  http://blog.llvm.org/2013/04/llvm-debianubuntu-nightly-packages.html
As I'm developing on Windows I can't really check if it actually works... sorry.

**Comment by eeide** [comment]
OK. I will work on this (and thanks for the pointer!). As I wrote, though, I won't be able to get to this for  few days.

**Comment by eeide** [comment]
(Background: Our new Travis-CI setup uses LLVM builds from <http://llvm.org/apt/>.)

I found a little time to experiment with this today. Here's a summary of what I learned.

Unless I'm mistaken, the LLVM folks don't provide nightly builds of the LLVM 3.7 branch at <http://llvm.org/apt/>. They created the LLVM 3.7.0 release SVN branch on July 14.

The development branch (I assume the SVN "trunk") described at http://llvm.org/apt/ currently provides access to nightly packages advertised as LLVM 3.8.

If I incorporate the C-Reduce code changes contained in this pull request, and also update our Travis-CI setup to build C-Reduce against the LLVM development branch, then the Travis-CI build succeeds. This is good news, but I'm unsure if it is the "right" thing to do.

Surely, if the next version of C-Reduce is expected to work with LLVM 3.7, then we should be building against the LLVM 3.7 branch. At the moment, I don't know how to get nightly builds of that branch for use in our Travis-CI setup.

**Comment by yrnkrn** [comment]
3.7 had just branched stablizing these days and will be released on Aug 21, at which time there would be binaries and sources and then branch may reasonably switch to 3.7.

Isn't llvm-svn-compatible branch supposed to be current LLVM svn compatible, unrelated to 3.7?

**Comment by eeide** [comment]
> Isn't llvm-svn-compatible branch supposed to be current LLVM svn compatible, unrelated to 3.7?

This is a good question :-). I think that the meaning of the "llvm-svn-compatible" branch has sometimes been fuzzy. In the past, we've used it to accumulate patches toward the next release version of LLVM. (And then to make a new C-Reduce release, we just merge the branch.)

If the "llvm-svn-compatible" branch is declared to be "compatible with the LLVM trunk," then it is possible—through maybe unlikely—that we wouldn't simply be able to merge the branch into the C-Reduce master branch in order to update C-Reduce for the then-current LLVM release. But I imagine that this would be pretty unlikely, and easy to deal with in any case.

I'm sure that I'm just overthinking it, since this is the first time I've had to deal with this issue for our Travis-CI stuff (since the Travis-CI stuff is new).

Surely you are right: the "right thing" is probably to do what I did, declare that "llvm-svn-compatible" is supposed to be compatible with the LLVM trunk, and just go with it. This is what I will do.

**Comment by eeide** [comment]
@chenyang78, would you like to review the actual code changes before I merge them into the llvm-svn-compatible branch? Thanks!

**Comment by chenyang78** [comment]
LGTM. 

Thanks for the patch, Yaron & thanks for taking care of it, Eric!

**Comment by eeide** [comment]
Thanks, @chenyang78! I will merge this pull request and then update the Travis-CI configuration on the "llvm-svn-compatible" branch.

**Comment by yrnkrn** [comment]
Thanks!

**Comment by mpflanzer** [comment]
LLVM 3.7 has just been released. :-) I guess it is time to merge the changes into the master branch. ;-)

**Comment by eeide** [comment]
Thank you for the heads up! Yes, it is time to update the C-Reduce master branch for LLVM 3.7 and make a new release. I'll take care of this in the next little while.

**Pull request merged**
