### PR TITLE
Add Dockerfile to locally emulate Travis-CI

### PR DESCRIPTION
**Pull request by tamird**
@eeide this should exercise the tests automatically. You'll need to set up travis-ci for the repo yourself, though.

[Review on Reviewable](https://reviewable.io/reviews/csmith-project/creduce/54)

### CODE REVIEW

**Comment by tamird** [comment]
(I've tested this on my fork, it passed: https://travis-ci.org/tamird/creduce/builds/61347988)

**Comment by tamird** [comment]
@eeide ping

**Comment by eeide** [comment]
I have not forgotten you.

**Comment by eeide** [comment]
Travis CI infrastructure for C-Reduce is really interesting (and useful)! Maybe this will push me to finally learn how to use Travis CI.

In the interest of getting an LLVM 3.6-compatible C-Reduce release done, I didn't incorporate this pull request into the C-Reduce 2.3.0 release. Sorry! I'd like to include this in a future release.

For Travis CI integration to be most useful, of course, C-Reduce needs some actual, functional, automatically runnable tests—which it does not yet have. This is another to-do for me, I guess.

**Comment by tamird** [comment]
Yep, that's right. In the meantime, this PR adds the facility to run those tests when they are incorporated in the future, and already does a basic sanity check that the code compiles and runs. It's worth merging as-is, I claim.

**Comment by regehr** [comment]
What's the status of this Eric?

**Comment by eeide** [comment]
The status (which I haven't communicated to anybody, thanks for the prod) is that I experimented with Travis-CI a while ago, and I've been meaning to get back to this issue. And since I'm here...

@tamird: I'd like to incorporate your Travis-CI work. Is it all right if we license the relevant files under the University of Illinois Open Source License? That is the license that we use for the rest of C-Reduce.

Right now, I only want to incorporate the Travis-CI files. I would be happy to extract the files from this pull request. If you prefer that I incorporate a pull request with those files, please give me one with only those files.

Thank you!

**Comment by tamird** [comment]
Why not include the Dockerfile? It's incredibly useful for locally testing what would happen in Travis.

I don't care about attribution, so feel free to take what you wish and license it any way you like.

**Comment by eeide** [comment]
I'd like to leave out the Dockerfile for now because I haven't yet reviewed it. I didn't mean to imply that I didn't like the Dockerfile.

(Like Travis-CI, this is a motivator for me to go off and actually use Docker.)

I will incorporate the Travis-CI-related files this weekend—thank you!

**Comment by eeide** [comment]
A quick note that I did not get to this task this weekend, due to a separate deadline. I hope to get back to this task later in the upcoming week. Sorry!

**Comment by eeide** [comment]
Hi! I added the Travis-CI-related files to C-Reduce a few days ago, on Wed Jul 22.

**Comment by tamird** [comment]
Rebased the PR and retitled.

**Comment by tamird** [comment]
@chenyang78 I've rebased this, in case it's of interest to you folks

**Comment by chenyang78** [comment]
Yes. 

Ping @eeide :)

**Comment by eeide** [comment]
Looks good to me!

@tamird, is it OK if we apply the University of Illinois Open Source License to your contribution? This is the same license as (most of) the rest of C-Reduce.

**Comment by tamird** [comment]
Yep, fine by me!

**Comment by eeide** [comment]
Merged. Thanks!

**Pull request merged**
