### PR TITLE
Compatibility for LLVM 11

### PR DESCRIPTION
**Pull request by jmperez-et**
This MR relies on berolinux changes for LLVM 10 support and adds further changes to to LLVM 11.

### CODE REVIEW

**Comment by eeide** [comment]
Thank you for your contribution!

Do you know if your changes different than those on the existing `llvm-11.0` branch?
https://github.com/csmith-project/creduce/tree/llvm-11.0

**Comment by jmperez-et** [comment]
Hi Eric,

My MR includes the unmodified commit from berolinux in MR #204 (cherry picked it) plus two additional commits which add the missing parts to update to LLVM 11. I hope this clarifies it.

BTW, thanks everyone in the project. It is amazing how useful and effective it is!

Cheers,
Josep M. Perez

**Comment by chenyang78** [comment]
@jmperez-et Thank you for the patch! Seems the patch does a similar fix as what we did for llvm-11.0 branch:

```
https://github.com/csmith-project/creduce/commit/3e1f5a1ec1365fafae965c97603221c9ccbc2d61
```

llvm-11.0 branch should work with LLVM 11. By the way, we don't actively maintain llvm-snv-compatible branch anymore. Instead, we have multiple branches that work with different LLVM releases at the moment. For example, we have llvm-11.0, llvm-12.0 and llvm-13.0 branches.

**Comment by jmperez-et** [comment]
Sorry, my bad. Somehow I did not realize there was already a branch for LLVM 11.

Cheers,
Josep M. Perez

**Comment by chenyang78** [comment]
> Sorry, my bad. Somehow I did not realize there was already a branch for LLVM 11. Cheers, Josep M. Perez

No problem at all, @jmperez-et ! Again, thank you for sharing you patch with us. Since the issue has been resolved, I am closing the pull request.

**Pull request closed without merging**
