### PR TITLE
Port to LLVM 15.0

### PR DESCRIPTION
**Pull request by berolinux**
This cherry-picks the commits needed to make the master branch build with LLVM 12.0 and 13.0 from the otherwise obsolete branches, and adds support for LLVM 15.0.

### CODE REVIEW

**Comment by chenyang78** [comment]
@berolinux Thank you for the patch! It looks good to me. I am holding off merging it until LLVM 15.0 is officially released. I checked LLVM's release schedule. Looks like it will happen pretty soon. Thanks!

**Comment by aganea** [comment]
Ping! Now LLVM 15.0 has been release, is someone able to merge this PR please?

**Comment by chenyang78** [comment]
LGTM. Thanks for contributing the patch!

**Comment by clausecker** [comment]
Could we get a new release now that LLVM 15 support is ready?

**Comment by regehr** [comment]
I hope so, this is very long overdue. but Eric is the person who cuts our releases so he will have to explain if he can make time for this.

**Comment by berolinux** [comment]
IMO it's not worth making a new release for LLVM 15 support, given by now LLVM 15 is obsolete already... Let's see if we can get LLVM 16 support in first...

**Comment by clausecker** [comment]
The last stable release supports LLVM 9 officially.  This is so outdated that we no longer ship it on FreeBSD.  Why not at least release something so distributions shipping your software can catch up?

**Comment by berolinux** [comment]
Posted LLVM 16 patch -- https://github.com/csmith-project/creduce/pull/254

Might as well go with that while at it.

**Comment by clausecker** [comment]
@berolinux If you cut a release based on that patch, I'm fine with that, too (have not tested it yet though).

**Pull request merged**
