### PR TITLE
Add a pass to remove constant ifs

### PR DESCRIPTION
**Pull request by amykhuang**
This adds a part to pass_unifdef that removes constant #if statements. The reordering is for the possibility that includes get nested under ifs.

### CODE REVIEW

**Comment by regehr** [comment]
I can review this
but @amykhuang can you look into the CI failure?

**Comment by regehr** [comment]
argh why are we still on LLVM 6? I guess we all tend to get distracted by other stuff

**Comment by eeide** [comment]
Well, I just haven't had time to update the Travis-CI configuration yet.

**Comment by regehr** [comment]
so the CI failure isn't a reflection on this PR? I can just review it?

**Comment by eeide** [comment]
Yes.

**Comment by regehr** [comment]
LGTM, thanks!

**Pull request merged**
